# Generated by Django 2.0 on 2018-05-22 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('sessionid', models.BigIntegerField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('accelerationx', models.FloatField(blank=True, null=True)),
                ('accelerationy', models.FloatField(blank=True, null=True)),
                ('accelerationz', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('batconsumptionperhour', models.FloatField(blank=True, null=True)),
                ('batterylevel', models.FloatField(blank=True, null=True)),
                ('devicebearing', models.FloatField(blank=True, null=True)),
                ('devicepitch', models.FloatField(blank=True, null=True)),
                ('deviceroll', models.FloatField(blank=True, null=True)),
                ('gps_bearing', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('lumen', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('proximity', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('vehiclemode', models.IntegerField(blank=True, null=True)),
                ('serialversionuid', models.BigIntegerField(blank=True, null=True)),
                ('color', models.BigIntegerField(blank=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('the_geom', models.TextField(blank=True, null=True)),
                ('field_id', models.UUIDField(db_column='_id')),
                ('vehicle_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'datapoints',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('epc', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lastupdate', models.DateTimeField(blank=True, null=True)),
                ('model', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
                ('brand', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('field_id', models.UUIDField(blank=True, db_column='_id', null=True)),
                ('lastposition', models.ForeignKey(blank=True, db_column='lastposition', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vehicles.Datapoint')),
                ('owner', models.ForeignKey(blank=True, db_column='owner', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registration.User')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vehicle_status',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('icon', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehicle_types',
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vehicles.Vehicle'),
        ),
    ]
