# Generated by Django 2.0.5 on 2018-05-25 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_update', models.DateTimeField(auto_now=True, db_column='lastupdate')),
                ('bike_type', models.CharField(choices=[('racing', 'racing'), ('city', 'city'), ('mountain', 'mountain'), ('foldable', 'foldable')], default='city', max_length=20)),
                ('gear', models.CharField(choices=[('single ring', 'single ring'), ('groupset below 18 speeds', 'groupset below 18 speeds'), ('groupset above 18 speeds', 'groupset above 18 speeds'), ('electric', 'electric')], default='groupset above 18 speeds', max_length=50)),
                ('brake', models.CharField(choices=[('disk', 'disk'), ('cantilever', 'cantilever'), ('coaster', 'coaster')], default='disk', max_length=30)),
                ('nickname', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('saddle', models.CharField(blank=True, max_length=100)),
                ('has_basket', models.BooleanField(default=False)),
                ('has_cargo_rack', models.BooleanField(default=False)),
                ('has_lights', models.BooleanField(default=False)),
                ('has_bags', models.BooleanField(default=False)),
                ('has_smb_sticker', models.BooleanField(default=False, verbose_name='has SaveMyBike sticker')),
                ('other_details', models.TextField()),
                ('last_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracks.CollectedPoint')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BikePossessionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possession_state', models.CharField(choices=[('with owner', 'with owner'), ('lost', 'lost'), ('stolen', 'stolen'), ('found by third party', 'found by third party')], default='with owner', max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Bike')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epc', models.TextField(help_text='Electronic Product Code')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Bike')),
            ],
        ),
    ]
