# Generated by Django 2.0.5 on 2018-06-01 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
        ('vehicles', '0002_auto_20180530_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='picture_gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery'),
        ),
    ]
