# Generated by Django 2.0.5 on 2018-06-04 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_bike_picture_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicaltag',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='vehicles.Bike'),
        ),
    ]
