# Generated by Django 2.0.5 on 2018-06-06 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_auto_20180604_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicaltag',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
