# Generated by Django 2.0.5 on 2018-06-07 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_physicaltag_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikepossessionhistory',
            options={'ordering': ['-creation_date']},
        ),
    ]
