# Generated by Django 2.0.5 on 2018-06-13 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0008_auto_20180608_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lost', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='vehicles.Bike')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.RemoveField(
            model_name='bikepossessionhistory',
            name='bike',
        ),
        migrations.RemoveField(
            model_name='bikepossessionhistory',
            name='reporter',
        ),
        migrations.DeleteModel(
            name='BikePossessionHistory',
        ),
    ]
