# Generated by Django 2.0.5 on 2018-06-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_auto_20180613_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicaltag',
            name='epc',
            field=models.TextField(help_text='Electronic Product Code', unique=True),
        ),
    ]
