# Generated by Django 2.0.5 on 2018-06-15 09:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_auto_20180614_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikestatus',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Bike last seen position', null=True, srid=4326),
        ),
    ]
