# Generated by Django 2.0.5 on 2018-06-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_bikestatus_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikestatus',
            name='reporter',
        ),
    ]
