# Generated by Django 2.0.5 on 2018-07-02 10:26

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_remove_bikestatus_reporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bike_type',
            field=models.CharField(choices=[('racing', 'racing'), ('city', 'city'), ('mountain', 'mountain'), ('foldable', 'foldable')], default='city', max_length=20, verbose_name='bike type'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='brake',
            field=models.CharField(choices=[('disk', 'disk'), ('cantilever', 'cantilevel'), ('coaster', 'coaster')], default='disk', max_length=30, verbose_name='brake'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='brand',
            field=models.CharField(blank=True, max_length=50, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='gear',
            field=models.CharField(choices=[('single ring', 'single ring'), ('groupset below 18 speeds', 'groupset below 18 speeds'), ('groupset above 18 speeds', 'groupset above 18 speeds'), ('electric', 'electric')], default='groupset above 18 speeds', max_length=50, verbose_name='gear'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='has_bags',
            field=models.BooleanField(default=False, verbose_name='has bags'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='has_basket',
            field=models.BooleanField(default=False, verbose_name='has basket'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='has_cargo_rack',
            field=models.BooleanField(default=False, verbose_name='has cargo rack'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='has_lights',
            field=models.BooleanField(default=False, verbose_name='has lights'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='last_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracks.CollectedPoint', verbose_name='last position'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='last_update',
            field=models.DateTimeField(auto_now=True, db_column='lastupdate', verbose_name='last update'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='model',
            field=models.CharField(blank=True, max_length=50, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='nickname',
            field=models.CharField(max_length=100, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='other_details',
            field=models.TextField(blank=True, verbose_name='other details'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='picture_gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery', verbose_name='picture_gallery'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='saddle',
            field=models.CharField(blank=True, max_length=100, verbose_name='saddle'),
        ),
        migrations.AlterField(
            model_name='bikestatus',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='vehicles.Bike', verbose_name='bike'),
        ),
        migrations.AlterField(
            model_name='bikestatus',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='bikestatus',
            name='details',
            field=models.TextField(blank=True, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='bikestatus',
            name='lost',
            field=models.BooleanField(default=False, verbose_name='lost'),
        ),
        migrations.AlterField(
            model_name='bikestatus',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Bike last seen position', null=True, srid=4326, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='physicaltag',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='vehicles.Bike', verbose_name='bike'),
        ),
        migrations.AlterField(
            model_name='physicaltag',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='physicaltag',
            name='epc',
            field=models.TextField(help_text='Electronic Product Code', unique=True, verbose_name='epc'),
        ),
    ]
