# Generated by Django 2.0.5 on 2018-07-04 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
        ('vehicles', '0013_auto_20180702_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikePicture',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('photologue.photo',),
        ),
    ]
