# Generated by Django 2.0.5 on 2018-07-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0014_bikepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='has_smb_sticker',
        ),
    ]
