# Generated by Django 2.0 on 2018-07-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_remove_bike_has_smb_sticker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='physicaltag',
            options={'ordering': ['creation_date']},
        ),
        migrations.AddField(
            model_name='bike',
            name='short_uuid',
            field=models.CharField(editable=False, max_length=8, null=True, verbose_name='short identifier'),
        ),
    ]
