# Generated by Django 2.0 on 2018-07-18 17:04

from django.db import migrations
import shortuuid


def add_short_uuid(apps, schema_editor):
    bike_model = apps.get_model("vehicles", "Bike")
    for bike in bike_model.objects.all():
        bike.short_uuid = shortuuid.encode(bike.id)[:8]
        bike.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_auto_20180718_1703'),
    ]

    operations = [
        migrations.RunPython(add_short_uuid, migrations.RunPython.noop)
    ]
