# Generated by Django 2.0 on 2018-07-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0017_data_migration_short_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='short_uuid',
            field=models.CharField(editable=False, max_length=8, unique=True, verbose_name='short identifier'),
        ),
    ]
