# Generated by Django 2.0 on 2018-09-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiondefinition',
            name='repeat_when',
            field=models.CharField(choices=[('repeat weekly', 'repeat each week'), ('repeat monthly', 'repeat each month'), ('repeat yearly', 'repeat each year'), ('repeat immediately', 'repeat immediately')], default='repeat immediately', help_text='If this competition is to be repeated, when should the next run start. If `immediately`, the new run will start on the next day after the previous one ends. If  one of the other options is selected, the next run will start on the same day as the previous, in the new temporal interval.', max_length=50, verbose_name='repeat when'),
        ),
    ]
