# Generated by Django 2.0 on 2018-09-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0002_auto_20180926_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='age_group',
            field=models.CharField(choices=[('< 19', '< 19'), ('19 - 30', '19 - 30'), ('30 - 65', '30 - 65'), ('65+', '65+'), ('compound_age_group', 'compound age group')], max_length=50, verbose_name='age group'),
        ),
    ]
