# Generated by Django 2.0 on 2018-10-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0002_auto_20181008_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionprize',
            name='prize_attribution_template',
            field=models.TextField(blank=True, help_text='Message shown to the user when the prize is won. This string is interpolated with a context that contains the following variables: score, rank', verbose_name='prize attribution template'),
        ),
    ]
