# Generated by Django 2.0 on 2018-10-02 16:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0003_auto_20180926_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentCompetition',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('prizes.competition',),
        ),
        migrations.AlterField(
            model_name='competition',
            name='age_group',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('< 19', '< 19'), ('19 - 30', '19 - 30'), ('30 - 65', '30 - 65'), ('65+', '65+')], max_length=10), size=4, verbose_name='age group'),
        ),
    ]
