# Generated by Django 2.0 on 2018-10-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0004_auto_20181018_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(help_text='Date when the competition ended', verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateTimeField(help_text='Date when the competition started', verbose_name='start date'),
        ),
    ]
