# Generated by Django 2.0 on 2019-06-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0005_auto_20181031_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='sponsors',
            field=models.ManyToManyField(blank=True, help_text='Sponsors for the competition', to='prizes.Sponsor'),
        ),
    ]
