# Generated by Django 2.0 on 2019-06-20 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prizes', '0006_competition_sponsors'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration_status', models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending_moderation', 'pending moderation')], max_length=100)),
                ('registration_justification', models.CharField(blank=True, help_text="A justification for the moderation of the user's request. Mostly useful as a means to let the user know why its participation request was rejected.", max_length=255)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prizes.Competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions_participating', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
