# Generated by Django 2.0 on 2019-06-20 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0007_competitionparticipant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winner',
            options={'ordering': ('rank', 'competition', 'user')},
        ),
        migrations.AddField(
            model_name='winner',
            name='participant',
            field=models.ForeignKey(blank=True, limit_choices_to={'registration_status': 'approved'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='prizes.CompetitionParticipant'),
        ),
    ]
