# Generated by Django 2.0 on 2019-06-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0009_convert_user_competition_to_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='participant',
            field=models.ForeignKey(limit_choices_to={'registration_status': 'approved'}, on_delete=django.db.models.deletion.CASCADE, to='prizes.CompetitionParticipant'),
        ),
    ]
