# Generated by Django 2.0 on 2019-06-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0010_auto_20190620_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winner',
            options={'ordering': ('rank', 'participant')},
        ),
    ]
