# Generated by Django 2.0 on 2019-06-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0011_auto_20190620_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='user',
        ),
    ]
