# Generated by Django 2.0 on 2019-07-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0013_pendingcompetitionparticipant_regionofinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='regions',
            field=models.ManyToManyField(blank=True, help_text='Regions of interest for the competition, if any', to='prizes.RegionOfInterest'),
        ),
    ]
