# Generated by Django 2.0 on 2018-05-22 23:41

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.User')),
                ('nickname', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('bio', models.CharField(max_length=200)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('date_updated', models.DateField(blank=True, null=True)),
                ('language_preference', models.IntegerField(blank=True, null=True)),
                ('level_of_sharing', models.IntegerField(blank=True, null=True)),
                ('profile_type', models.IntegerField(blank=True, null=True)),
                ('profile_icon', models.CharField(max_length=200)),
                ('profile_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('registration.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
