# Generated by Django 2.0.5 on 2018-05-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduserprofile',
            name='user_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='MEDIA.ROOT.ASSETS'),
        ),
    ]
