# Generated by Django 2.0.5 on 2018-05-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduserprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short user biography'),
        ),
    ]
