# Generated by Django 2.0.5 on 2018-05-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180528_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduserprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male')], max_length=20),
        ),
    ]
