# Generated by Django 2.0.5 on 2018-06-06 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180530_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enduserprofile',
            name='user_avatar',
        ),
    ]
