# Generated by Django 2.0.5 on 2018-06-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20180608_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilityhabitssurvey',
            name='bicycle_usage',
            field=models.CharField(choices=[('frequent', 'Habitual (at least once a week on average)'), ('occasional', 'Habitual (at least once a month)'), ('seasonal', 'Seasonal (mainly used in the Summer)'), ('rare', 'Rare (less than once a month)'), ('never', 'Never use a bicycle to move around in the city')], default='rare', max_length=100),
        ),
        migrations.AlterField(
            model_name='mobilityhabitssurvey',
            name='public_transport_usage',
            field=models.CharField(choices=[('frequent', 'Habitual (more than 10 travels per month)'), ('occasional', 'Occasional (once per month)'), ('rare', 'Rare (less than 10 travels per year)'), ('never', 'Never')], default='rare', max_length=100),
        ),
    ]
