# Generated by Django 2.0.5 on 2018-06-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20180608_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smbuser',
            name='cognito_user_status',
        ),
        migrations.RemoveField(
            model_name='smbuser',
            name='sub',
        ),
    ]
