# Generated by Django 2.0.5 on 2018-07-02 10:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20180614_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduserprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short user biography', verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='enduserprofile',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='enduserprofile',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], default='female', max_length=20, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='enduserprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\+\\d{8,15}$', message='Use the format +99999999. From 8 to 15 digits allowed')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='enduserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='mobilityhabitssurvey',
            name='bicycle_usage',
            field=models.CharField(choices=[('frequent', 'Habitual (at least once a week on average)'), ('occasional', 'Habitual (at least once a month)'), ('seasonal', 'Seasonal (mainly used in the Summer)'), ('rare', 'Rare (less than once a month)'), ('never', 'Never use a bicycle to move around in the city')], default='rare', max_length=100, verbose_name='bicycle usage'),
        ),
        migrations.AlterField(
            model_name='mobilityhabitssurvey',
            name='date_answered',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date answered'),
        ),
        migrations.AlterField(
            model_name='mobilityhabitssurvey',
            name='end_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobility_habits_surveys', to='profiles.EndUserProfile', verbose_name='end user'),
        ),
        migrations.AlterField(
            model_name='mobilityhabitssurvey',
            name='public_transport_usage',
            field=models.CharField(choices=[('frequent', 'Habitual (more than 10 travels per month)'), ('occasional', 'Occasional (once per month)'), ('rare', 'Rare (less than 10 travels per year)'), ('never', 'Never')], default='rare', max_length=100, verbose_name='public transport usage'),
        ),
        migrations.AlterField(
            model_name='mobilityhabitssurvey',
            name='uses_bike_sharing_services',
            field=models.BooleanField(default=False, verbose_name='uses bike sharing services'),
        ),
        migrations.AlterField(
            model_name='mobilityhabitssurvey',
            name='uses_electrical_car_sharing_services',
            field=models.BooleanField(default=False, verbose_name='uses electrical car sharing services'),
        ),
        migrations.AlterField(
            model_name='mobilityhabitssurvey',
            name='uses_fuel_car_sharing_services',
            field=models.BooleanField(default=False, verbose_name='uses fuel car sharing services'),
        ),
        migrations.AlterField(
            model_name='privilegeduserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='smbuser',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italian')], default='en', max_length=20, verbose_name='language preference'),
        ),
        migrations.AlterField(
            model_name='smbuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='nickname'),
        ),
    ]
