# Generated by Django 2.0.5 on 2018-07-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20180702_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduserprofile',
            name='age',
            field=models.CharField(choices=[('< 19', '< 19'), ('19 - 30', '19 - 30'), ('30 - 65', '30 - 65'), ('65+', '65+')], default='19 - 30', max_length=20, verbose_name='age'),
        ),
    ]
