# Generated by Django 2.0.5 on 2018-07-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('profiles', '0012_smbuser_accepted_terms_of_service'), ('profiles', '0013_auto_20180710_1632'), ('profiles', '0014_auto_20180710_1634'), ('profiles', '0015_auto_20180710_1706')]

    dependencies = [
        ('profiles', '0011_enduserprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='smbuser',
            name='accepted_terms_of_service',
            field=models.BooleanField(default=False, verbose_name='I accept the portal Terms of Service'),
        ),
    ]
