# Generated by Django 2.0 on 2018-08-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_enduserprofile_occupation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smbuser',
            options={'ordering': ['date_joined']},
        ),
        migrations.AlterField(
            model_name='smbuser',
            name='accepted_terms_of_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='smbuser',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italian')], default='it', max_length=20, verbose_name='language preference'),
        ),
    ]
