# Generated by Django 2.0 on 2018-09-18 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_gamification', '0013_auto_20180324_0605'),
        ('profiles', '0014_auto_20180806_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='smbuser',
            name='gamification_interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gamification.GamificationInterface', verbose_name='gamification interface'),
        ),
    ]
