# Generated by Django 2.0 on 2018-09-18 09:40

from django.db import migrations


def add_gamification_interface(apps, schema_editor):
    user_model = apps.get_model("profiles", "SmbUser")
    gamification_interface_model = apps.get_model(
        "django_gamification", "GamificationInterface")
    for user in user_model.objects.all():
        if user.gamification_interface is None:
            iface = gamification_interface_model()
            iface.save()
            user.gamification_interface = iface
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_smbuser_gamification_interface'),
        ('django_gamification', '0013_auto_20180324_0605'),
    ]

    operations = [
        migrations.RunPython(add_gamification_interface)
    ]
