# Generated by Django 2.0 on 2018-09-18 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_add-gamification-interface-to-users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smbuser',
            name='gamification_interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_gamification.GamificationInterface', verbose_name='gamification interface'),
        ),
    ]
