# Generated by Django 2.0.5 on 2018-06-13 16:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeobservation',
            name='address',
            field=models.CharField(blank=True, help_text='Approximate address. Either this field or `position` must be given', max_length=255),
        ),
        migrations.AlterField(
            model_name='bikeobservation',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Either this field or `address` must be given', null=True, srid=4326),
        ),
    ]
