# Generated by Django 2.0.5 on 2018-07-11 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemonitor', '0003_auto_20180702_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikeobservation',
            name='reporter',
        ),
    ]
