# Generated by Django 2.0.5 on 2018-07-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemonitor', '0005_auto_20180711_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeobservation',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='reporter name'),
        ),
    ]
