# Generated by Django 2.0.5 on 2018-05-25 15:15

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(blank=True, help_text='Identifier of the vehicle used, if any', max_length=255, null=True)),
                ('vehicle_type', models.CharField(blank=True, choices=[('bike', 'bike'), ('bus', 'bus')], default='bike', max_length=50, null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('accelerationx', models.FloatField(blank=True, null=True)),
                ('accelerationy', models.FloatField(blank=True, null=True)),
                ('accelerationz', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('batconsumptionperhour', models.FloatField(blank=True, null=True)),
                ('batterylevel', models.FloatField(blank=True, null=True)),
                ('devicebearing', models.FloatField(blank=True, null=True)),
                ('devicepitch', models.FloatField(blank=True, null=True)),
                ('deviceroll', models.FloatField(blank=True, null=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('gps_bearing', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('lumen', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('proximity', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('icon_color', models.BigIntegerField(blank=True, null=True)),
                ('sessionid', models.BigIntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='collectedpoint',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.Track'),
        ),
    ]
