# Generated by Django 2.0.5 on 2018-06-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectedpoint',
            name='owner',
        ),
    ]
