# Generated by Django 2.0 on 2018-07-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_remove_collectedpoint_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectedpoint',
            name='collection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
