# Generated by Django 2.0 on 2018-07-18 21:41

import datetime as dt

from django.db import migrations
import pytz


def convert_timestamp_to_datetime(apps, schema_editor):
    """Convert a timestamp given in milliseconds to a datetime"""
    collected_point_model = apps.get_model("tracks", "CollectedPoint")
    for pt in collected_point_model.objects.all():
        if pt.timestamp is not None:
            pt.collection_date = dt.datetime.fromtimestamp(
                pt.timestamp / 1000,
                pytz.utc
            )
            pt.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_collectedpoint_collection_date'),
    ]

    operations = [
        migrations.RunPython(
            convert_timestamp_to_datetime, migrations.RunPython.noop)
    ]
