# Generated by Django 2.0 on 2018-07-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_data_migration_convert_timestamp_to_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectedpoint',
            name='timestamp',
        ),
    ]
