# Generated by Django 2.0 on 2018-07-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_remove_collectedpoint_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectedpoint',
            old_name='collection_date',
            new_name='timestamp',
        ),
    ]
