# Generated by Django 2.0 on 2018-08-06 13:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bossoidc', '0001_initial'),
        ('tracks', '0006_auto_20180718_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bike', 'bike'), ('bus', 'bus'), ('car', 'car'), ('foot', 'foot')], max_length=20, verbose_name='vehicle type')),
                ('the_geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326, verbose_name='geometry')),
                ('start_date', models.DateTimeField(help_text='timestamp of first collected point of the segment', verbose_name='start date')),
                ('end_date', models.DateTimeField(help_text='timestamp of last collected point of the segment', verbose_name='end date')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.Track', verbose_name='track')),
                ('user_uuid', models.ForeignKey(db_column='user_uuid', on_delete=django.db.models.deletion.CASCADE, to='bossoidc.Keycloak', verbose_name='user uuid')),
            ],
        ),
    ]
