# Generated by Django 2.0 on 2018-08-06 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0007_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so2', models.FloatField(blank=True, help_text='Sulphur Dioxide emissions (mg)', null=True, verbose_name='SO2')),
                ('so2_saved', models.FloatField(blank=True, help_text='Dulphur Dioxide emissions that were prevented (mg)', null=True, verbose_name='SO2 saved')),
                ('nox', models.FloatField(blank=True, help_text='Nitrogen Oxides emissions (mg)', null=True, verbose_name='NOx')),
                ('nox_saved', models.FloatField(blank=True, help_text='Nitrogen Oxides emissions that were prevented (mg)', null=True, verbose_name='NOx saved')),
                ('co2', models.FloatField(blank=True, help_text='Carbon dioxide emissions (g)', null=True, verbose_name='CO2')),
                ('co2_saved', models.FloatField(blank=True, help_text='Carbon dioxide emissions that were prevented (g)', null=True, verbose_name='CO2 saved')),
                ('co', models.FloatField(blank=True, help_text='Carbon monoxide emissions (mg)', null=True, verbose_name='CO')),
                ('co_saved', models.FloatField(blank=True, help_text='Carbon monoxide emissions that were prevented (mg)', null=True, verbose_name='CO saved')),
                ('pm10', models.FloatField(blank=True, help_text='Particulate Matter up to 10um emissions (mg)', null=True, verbose_name='PM10')),
                ('pm10_saved', models.FloatField(blank=True, help_text='Particulate Matter up to 10um emissions that were prevented (mg)', null=True, verbose_name='PM10 saved')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.Segment', verbose_name='segment')),
            ],
        ),
    ]
