# Generated by Django 2.0 on 2018-08-06 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0008_emission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_cost', models.FloatField(blank=True, help_text='Fuel consumption cost (eur)', null=True, verbose_name='fuel cost')),
                ('time_cost', models.FloatField(blank=True, help_text='Time spent cost (eur)', null=True, verbose_name='time cost')),
                ('depreciation_cost', models.FloatField(blank=True, help_text='Vehicle depreciation cost (eur)', null=True, verbose_name='depreciation cost')),
                ('operation_cost', models.FloatField(blank=True, help_text='Vehicle operation cost (eur)', null=True, verbose_name='operational cost')),
                ('total_cost', models.FloatField(blank=True, help_text='Total cost (eur)', null=True, verbose_name='total cost')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.Segment', verbose_name='segment')),
            ],
        ),
    ]
