# Generated by Django 2.0 on 2018-08-06 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0009_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories_consumed', models.FloatField(blank=True, help_text='Calories consumed (cal)', null=True, verbose_name='calories consumed')),
                ('benefit_index', models.FloatField(blank=True, help_text="Benefit Index, adapted from World Health Organization's 'Health economic assessment tools (HEAT) for walking and for cycling - Methods and user guide on physical activity, air pollution, injuries and carbon impact assessments'", null=True, verbose_name='benefit index')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.Segment', verbose_name='segment')),
            ],
        ),
    ]
