# Generated by Django 2.0 on 2018-08-07 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0010_health'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectedpoint',
            options={'ordering': ['timestamp']},
        ),
    ]
