# Generated by Django 2.0 on 2018-08-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0011_auto_20180807_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectedpoint',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('bike', 'bike'), ('bus', 'bus'), ('car', 'car'), ('foot', 'foot'), ('motorbike', 'motorbike'), ('scooter', 'scooter')], default='bike', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'bike'), ('bus', 'bus'), ('car', 'car'), ('foot', 'foot'), ('motorbike', 'motorbike'), ('scooter', 'scooter')], max_length=20, verbose_name='vehicle type'),
        ),
    ]
