# Generated by Django 2.0 on 2018-08-09 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0012_auto_20180808_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='segment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracks.Segment', verbose_name='segment'),
        ),
    ]
