# Generated by Django 2.0 on 2018-08-29 16:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0016_auto_20180810_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326, verbose_name='geometry'),
        ),
    ]
