# Generated by Django 2.0 on 2018-08-29 16:35

from django.contrib.gis import geos
from django.db import migrations


def provide_default_geom(apps, schema_editor):
    segment_model = apps.get_model("tracks", "Segment")
    for segment in segment_model.objects.all():
        segment.geom = geos.LineString()
        segment.save()


def nullify_default_geom(apps, schema_editor):
    segment_model = apps.get_model("tracks", "Segment")
    for segment in segment_model.objects.all():
        if segment.geom is not None and segment.geom.empty:
            segment.geom = None
        segment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0018_remove_segment_the_geom'),
    ]

    operations = [
        migrations.RunPython(provide_default_geom, nullify_default_geom),
    ]
