# Generated by Django 2.0 on 2018-08-30 08:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0019_data_migration_remove_geom_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='geometry'),
        ),
    ]
