# Generated by Django 2.0 on 2018-08-30 14:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0020_auto_20180830_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='aggregated_costs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="Aggregated costs for the track's segments, for each vehicle type. These are pre-computed from segment data in order to improve runtime performance.", null=True, verbose_name='aggregated costs'),
        ),
        migrations.AddField(
            model_name='track',
            name='aggregated_emissions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="Aggregated emissions for the track's segments, for each vehicle type. These are pre-computed from segment data in order to improve runtime performance.", null=True, verbose_name='aggregated emissions'),
        ),
        migrations.AddField(
            model_name='track',
            name='aggregated_health',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="Aggregated health data for the track's segments, for each vehicle type. These are pre-computed from segment data in order to improve runtime performance.", null=True, verbose_name='aggregated health'),
        ),
    ]
