# Generated by Django 2.0 on 2018-09-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0021_auto_20180830_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['created_at']},
        ),
    ]
