# Generated by Django 2.0 on 2018-09-03 14:37

from django.db import migrations


def add_session_id(apps, schema_editor):
    track_model = apps.get_model("tracks", "Track")
    for track in track_model.objects.all():
        if track.session_id is None:
            track.session_id = track.id
            track.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0023_track_session_id'),
    ]

    operations = [
        migrations.RunPython(add_session_id),
    ]
