# Generated by Django 2.0 on 2018-09-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0024_add_sessionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='session_id',
            field=models.BigIntegerField(unique=True, verbose_name='session id'),
        ),
    ]
