# Generated by Django 2.0 on 2018-09-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0025_auto_20180903_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.FloatField(blank=True, help_text='Track duration, measured in minutes', null=True, verbose_name='duration'),
        ),
        migrations.AddField(
            model_name='track',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='track',
            name='length',
            field=models.FloatField(blank=True, help_text='Track length, measured in meters', null=True, verbose_name='length'),
        ),
        migrations.AddField(
            model_name='track',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start date'),
        ),
    ]
