# Generated by Django 2.0 on 2018-09-07 10:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0026_auto_20180907_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326, verbose_name='geometry'),
        ),
    ]
