# Generated by Django 2.0 on 2018-09-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0027_track_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectedpoint',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('bike', 'bike'), ('bus', 'bus'), ('car', 'car'), ('foot', 'foot'), ('motorcycle', 'motorcycle'), ('train', 'train')], default='bike', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'bike'), ('bus', 'bus'), ('car', 'car'), ('foot', 'foot'), ('motorcycle', 'motorcycle'), ('train', 'train')], max_length=20, verbose_name='vehicle type'),
        ),
    ]
