# Generated by Django 2.0 on 2018-10-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0029_regionofinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_valid',
            field=models.BooleanField(default=False, help_text='If the track has passed the ingestion validation pipeline', verbose_name='is valid'),
        ),
        migrations.AddField(
            model_name='track',
            name='validation_error',
            field=models.TextField(blank=True, help_text='Reason for the track not being valid', verbose_name='validation error'),
        ),
    ]
