# Generated by Django 2.0 on 2018-10-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0030_auto_20181018_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-start_date']},
        ),
    ]
