# Generated by Django 2.0 on 2019-07-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0031_auto_20181024_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegionOfInterest',
        ),
    ]
